<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Opencode.ConsoleChatSample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Opencode.Sdk/Opencode.Sdk.csproj" />
    </ItemGroup>

</Project>